### ISSUE TITLE
Font rendering on retina display

### ISSUE THREAD

**Issue by unknowndevice** [Planimeter/grid-sdk#10]
You probably already know this but the font is pretty bad looking on retina displays ![screen shot 2015-05-04 at 23 57 41](https://cloud.githubusercontent.com/assets/4682853/7464272/7692e59c-f2b9-11e4-9012-b357a89d9c6b.png)

**Comment by andrewmcwatters** [comment]
Whoa, that is gross nasty. Unfortunately, I do not have any retina devices to test this on. I'll try enabling retina functionality through Grid's default LÖVE configuration and get back to you ASAP on this one.

Thank you for reporting this! You did the right thing; if we don't have it in the issue tracker, assume that we're oblivious.

**Comment by andrewmcwatters** [comment]
I've just pushed a code drop for build 787, so now in [Grid's default LÖVE configuration](https://github.com/Planimeter/grid-sdk/blob/master/src/conf.lua#L61) we enable high-dpi mode.

@unknowndevice Could you give me a heads up and tell me if that fixes at least the typographical issues? The other assets in the game should still be affected, and I'll try to take care of them ASAP, but that's a separate issue for now.

**Comment by andrewmcwatters** [comment]
Actually relabeling this with help wanted, because it's out of my power to test.

**Comment by unknowndevice** [comment]
I'll test it now.

**Comment by unknowndevice** [comment]
Font rendering is better now. Just the scaling is incorrect 
![screen shot 2015-05-05 at 15 30 41](https://cloud.githubusercontent.com/assets/4682853/7474846/d6b3f146-f33b-11e4-9269-452f50f94665.png)
![screen shot 2015-05-05 at 15 31 09](https://cloud.githubusercontent.com/assets/4682853/7474845/d6b10918-f33b-11e4-8905-5021f37457a8.png)

**Comment by andrewmcwatters** [comment]
Thanks again for taking the time to report this! :heart:

**Comment by unknowndevice** [comment]
I'm using the macbook pro retina late 2013!

No problem, I think it's an interesting project!

**Comment by andrewmcwatters** [comment]
Dismissing this for now. This is planned to be fully supported in the future, but at the moment I can't address the issue.
