### ISSUE TITLE
love 11.x support

### ISSUE THREAD

**Issue by srdgame** [Planimeter/grid-sdk#100]
I have tried to run grid-sdk, which is wonderful with love 0.10.2.

As love as released 11.x in 2018, it is better that upgrade grid-sdk with love 11.x.

**Comment by andrewmcwatters** [comment]
There's a build of Grid currently on LÖVE 11 which has not yet been released. I'll schedule this for deployment tonight. It's probably time I get it out in the open.

**Comment by andrewmcwatters** [comment]
Resolved in [`v8.0.0`](https://github.com/Planimeter/grid-sdk/releases/tag/v8.0.0).
