### ISSUE TITLE
Pathing hogs system resources while it calculates.

### ISSUE THREAD

**Issue by ryan-kingstone** [Planimeter/grid-sdk#11]
Just leaving this here briefly.

Could A* be a better alternative by any chance?

**Comment by andrewmcwatters** [comment]
Unless I'm somehow naively mistaken and the implementation is wrong, what the `path` interface uses is an A* algorithm.

Can you tell me how the interface hogs resources so I can try to optimize it?

**Comment by ryan-kingstone** [comment]
I am unsure of exactly which point in the algorithm the issue may lie, but if I for instance run a server in debug, and a client in debug at once, and then initiate a pathfinding using rightclick via the client, the client tends to freeze for an extended period of time until the calculations are done, I believe.

**Comment by andrewmcwatters** [comment]
Okay, that shouldn't happen, thanks for the heads up. I'll make sure to look into this.

**Comment by ryan-kingstone** [comment]
Resource hog would appear to originate from cl_payload_show_receive being set to 1, as having it set to 0 does not have the same impact on the client.

**Comment by ryan-kingstone** [comment]
(It's most likely due to the quick succession of the prints)

**Comment by andrewmcwatters** [comment]
Ah yes, this is definitely an issue with `cl_payload_show_receive 1`. Any print heavy ops are expensive just because of the incurred buffering in cmd as well as the in-game console. though I believe it should be defaulted off as of a few builds back.

**Comment by andrewmcwatters** [comment]
If you can confirm that, I'll mark this invalid if you'd like.

**Comment by ryan-kingstone** [comment]
I can confirm. It's not a hog while the convar is set to 0.

**Comment by andrewmcwatters** [comment]
:+1:
