### ISSUE TITLE
Profile library might be broken?

### ISSUE THREAD

**Issue by ryan-kingstone** [Planimeter/grid-sdk#17]
I think it could perhaps be broken, or I'm doing some stupid error.
```lua
function thefunction(args)
    profile.start("a")
    **function code**
    profile.stop("a")
end
```

The above does cause an error which goes along the lines of 'attempt to index global 'profile' (a nil value) on profile.start(), this might be an user error, not necesarily something broken, just need new eyes on it.

**Comment by andrewmcwatters** [comment]
Hey Ryan, the profiler isn't loaded by default in the engine anywhere at the moment. Add `require( "engine.shared.profile" )` before those lines.

**Comment by ryan-kingstone** [comment]
I did add that. Still receiving the same issue.

**Comment by andrewmcwatters** [comment]
If you're doing this in a module, make sure to access it from `_G`, `_G.profile`, etc.

**Comment by ryan-kingstone** [comment]
I believe that was the issue. Thank-you. Would be useful to have somewhere in the wiki.

**Comment by andrewmcwatters** [comment]
I'll make sure to document this from now on in the various interfaces and libraries. It's important to know when stuff is available. Thanks for bringing this up!
