### ISSUE TITLE
Grid should probably have an audio interface built into itself.

### ISSUE THREAD

**Issue by ryan-kingstone** [Planimeter/grid-sdk#18]
Löve2D's audio interface does lack in certain departments.

Features that probably should be in the interface:
- Volume based on distance?
- Sound effects - underwater, etc. (This is not a required, but still useful feature).
- Equalization, Bass boost, etc?

(This is just an idea, not a requirement!)

**Comment by andrewmcwatters** [comment]
You're right. This was planned but I didn't stub it out yet.

**Comment by andrewmcwatters** [comment]
It's funny, because we give an example for `entity:emitSound()` on the front page!

**Comment by andrewmcwatters** [comment]
Dismissing this for now.
