### ISSUE TITLE
Grid graphics crashes on startup (Windows 7 x64)

### ISSUE THREAD

**Issue by Dasomeone** [Planimeter/grid-sdk#22]
Attempting to run the engine in debug mode, from fresh direct clone of current repo (commit 19b68ed5cf7ac331f513b640c6bc1ee5e5243089) gives: 
> Error: engine/client/graphics.lua:64: bad argument #1 to 'draw' )Drawable expected, got table)

> stack traceback:
>     [C]: in function 'draw'
>     engine/client/graphics.lua:64: in function 'draw'
>     engine/client/graphics.lua:113: in function 'drawGrid'
>     engine/client/init.lua:158: in function 'draw'
>     [string "boot.lua"]:427: in function ([string "boot.lua"]:389)
>     [C]: in function 'xpcall'

**Comment by andrewmcwatters** [comment]
There's something quite wrong here, as I cannot seem to replicate it on my end, nor any of the other Planimeter developers have seen this. Fresh clone of `master`. Going to mark as test anyway and see if any other team member can replicate.

**Comment by Dasomeone** [comment]
It's a fresh clone of master, on a fresh Löve install on a fresh Win7 x64 VM. I can spin up another fresh one and re-test if you'd like?

**Comment by andrewmcwatters** [comment]
We have binaries that ship with the repo and are referenced in the batch files, but it should work with LÖVE 0.9.2 just fine. If it isn't, we've broken something or we need to update the binaries in `/bin`.

**Comment by andrewmcwatters** [comment]
I'll try and take a stab at this tomorrow to confirm. Gotta head off to bed! Thank you for reporting this, though!

**Comment by andrewmcwatters** [comment]
Due to the VM environment, we're marking this as invalid for now.
