### ISSUE TITLE
Add support for server MySQL database interaction.

### ISSUE THREAD

**Issue by ryan-kingstone** [Planimeter/grid-sdk#26]
title.

**Comment by vrondakis** [comment]
+1

**Comment by andrewmcwatters** [comment]
I feel like this is outside of the scope of Grid, but I can't ignore the fact that I've seen this lightly implemented through SQLite in other places like Garry's Mod, etc.

**Comment by andrewmcwatters** [comment]
Closing this for now, please feel free to reopen if anyone would like to be sponsored by us for this project as a separate module or addon for Grid. My plate is currently too full to take this on.
