### ISSUE TITLE
Implement advanced keyboard options

### ISSUE THREAD

**Issue by andrewmcwatters** [Planimeter/grid-sdk#4]
Clicking on "Advanced" in the keyboard options menu should bring up a modal allowing the user to toggle things like enabling the developer console.

**Comment by ryan-kingstone** [comment]
Might push towards this feature over the weekend unless it's a 1.0.0 thing.

**Comment by andrewmcwatters** [comment]
We can push it in with v1.0.0 if you'd like.

**Comment by andrewmcwatters** [comment]
If you're interested in being listed on [/planimeter](http://www.andrewmcwatters.com/planimeter/) for your contributions, give me a heads up, too.

**Comment by ryan-kingstone** [comment]
Yeah, sure. I'm a resident of Oslo, Norway.

**Comment by ryan-kingstone** [comment]
So, the panel should have developer console checkbox + ?

**Comment by andrewmcwatters** [comment]
Cool, welcome to Planimeter.

Also yeah, pretty much just a checkbox for the developer console at the moment. Pretty bleak, but yeah.

**Comment by andrewmcwatters** [comment]
Sorry for the delay! This is merged and ready for `v1.0.0`. Dropping the `beta` tag after this release.

**Comment by andrewmcwatters** [comment]
Pending code drop downstream from `vertex-adventure`.

**Comment by andrewmcwatters** [comment]
Fixed in build 806
