### ISSUE TITLE
Add sound functionality

### ISSUE THREAD

**Issue by ryan-kingstone** [Planimeter/grid-sdk#42]

**Comment by andrewmcwatters** [comment]
Adding low priority to this because while it's important, we have to clear out existing bugs first.

**Comment by andrewmcwatters** [comment]
TODO:

`entity:emitSound()`
`gui.playSound()`

Add others here if you can think of them.

**Comment by ryan-kingstone** [comment]
entity:emitSound(range, sound)

**Comment by andrewmcwatters** [comment]
Closing this for now. We'll come back to this, but we have a lot of textbox and chat related stuff to take care of first.
