### ISSUE TITLE
Move game-related code out of engine

### ISSUE THREAD

**Issue by andrewmcwatters** [Planimeter/grid-sdk#59]
Request for functionality to move out of `engine` and into `game` for `1.7.0` scheduled this weekend.

Proposed moves:

- [ ] `engine.shared.entities.entity`
- [x] `engine.shared.entities.npc`
- [x] `engine.shared.entities.player`

**Comment by andrewmcwatters** [comment]
@ryan-kingstone Wanna help me coordinate this? I'm not sure what we want to move. I think these are a start though. Might be it? Not sure.

**Comment by ryan-kingstone** [comment]
Currently on a limited mobile connection. I've ticked the ones who should go into /game.

**Comment by andrewmcwatters** [comment]
:+1:

**Comment by andrewmcwatters** [comment]
Actually sort of debating this after I noticed the pattern of everything VA-related being in `game`, and anything base class related being in `engine`.

**Comment by andrewmcwatters** [comment]
Postponing this for now.
