### ISSUE TITLE
Add task queue for characters

### ISSUE THREAD

**Issue by andrewmcwatters** [Planimeter/grid-sdk#66]
Rough draft sample API:

```lua
local function moveTo( position )
  return function( player, next )
    player:moveTo( position, next )
  end
end

local function pickupItem( item )
  return function( player, next )
    if ( not item or not item:isValid() ) then
      return next()
    end

    local classname = item:getClassname()
    item:remove()
    player:give( classname )
    next()
  end
end

function player:pickupItem( item )
  local pos = item:getPosition()
  self:addTask( moveTo( pos ) )
  self:addTask( pickupItem( item ) )
end

-- character:addTask( function( character, next )[, taskName ] )
-- character:removeTask( taskName )
-- character:removeTasks()
```

**Comment by ryan-kingstone** [comment]
I think the API should include a queue system so people can stack up tasks. Unless I'm stupid and missed something.

**Comment by andrewmcwatters** [comment]
`character:addTask()` is like a task insert.

**Comment by ryan-kingstone** [comment]
Excellent. Should each individual task have a "duration" argument so it can specify a "minimum" end time or does it just go through until "end" ?

**Comment by andrewmcwatters** [comment]
It's delegated to the task handler, so you basically have to call `next()` from your task to give up control. In the case of the `moveTo()` task above, I just pass `next` as a callback to `character:moveTo()`, thus calling `next()` when the player has arrived.

**Comment by andrewmcwatters** [comment]
I think a system like this would allow us to interrupt tasks in the event you were attacked, or a quest needed to override your task queue, etc.

**Comment by ryan-kingstone** [comment]
Yeah, good planning.

**Comment by andrewmcwatters** [comment]
Pending `downstream` merge to `grid-sdk` from `build 1141`.
