### ISSUE TITLE
CODE DROP

### ISSUE THREAD

**Issue by Rohansi** [Planimeter/grid-sdk#73]

**Comment by skooch** [comment]
meme

**Comment by andrewmcwatters** [comment]
big meme

**Comment by skooch** [comment]
enormously dank meme

**Comment by andrewmcwatters** [comment]
colossal fresh dank meme

**Comment by krixalis** [comment]
:eggplant:

**Comment by HandsomeMatt** [comment]
code drop

sup skooch

**Comment by skooch** [comment]
@HandsomeMatt oh my...........................

**Comment by GranPC** [comment]
oops

**Comment by andrewmcwatters** [comment]
someone pick it up, i need help here

**Comment by ryan-kingstone** [comment]
I'll pick it up and drop it against a rock <3

**Comment by andrewmcwatters** [comment]
pick it up and throw it at @ZehM4tt

**Comment by Rohansi** [comment]
stop using dropbox for version control pls
On May 27, 2016 3:26 PM, Andrew McWatters <notifications@github.com> wrote:pick it up and throw it at @ZehM4tt

**Comment by andrewmcwatters** [comment]
this repo is a just a mirror of our private `vertex-adventure` repository on bitbucket, with some modifications for the public

**Comment by Rohansi** [comment]
source open......not open source..........disappointed.........

**Comment by andrewmcwatters** [comment]
rms cries every time i push a commit, because he knows my real intentions
