### ISSUE TITLE
Documentation | Examples

### ISSUE THREAD

**Issue by stonecauldron** [Planimeter/grid-sdk#74]
Is there any documentation about the engine?

Or some game examples?

**Comment by andrewmcwatters** [comment]
Hi! We're currently reconstructing the engine's tutorials and API documentation. At the moment, it's for advanced users who are able to read through the sample code provided.

**Comment by stonecauldron** [comment]
I see, thank you for the information.

**Comment by andrewmcwatters** [comment]
Planning on adding Getting Started articles back sometime this week.
