### ISSUE TITLE
Error on Start when Fullscreen is enabled

### ISSUE THREAD

**Issue by BratwurstMitSenf** [Planimeter/grid-sdk#80]
When Fullscreen is enabled in the Settings, the following error is thrown at startup:
![err](https://cloud.githubusercontent.com/assets/3192999/18558998/939b6de4-7b75-11e6-8936-81e1395ec2b9.png)

It seems that the clientwindow is started up in windowed and then resized to fullscreen before the framebuffer is initialized, leading to the nullreference exception inside the eventhandler.

I didn't have time to dive into it yet, since i just found it today during lunchbreak. I'll try to find a fix this weekend and send a patch.

Otherwise thank's for this fine piece of software. I'm very impressed so far. :wink:

**Comment by andrewmcwatters** [comment]
Hey, thanks for reporting this issue! Just curious, since we're in the middle of this engine-wide refactor, was this in `master`/`v8.0.0`?

I have some patches upstream from our flagship game, which uses Grid, and I should be able to merge this back to `grid-sdk`.

**Comment by andrewmcwatters** [comment]
I'm guessing this must be from the latest, since it's from the client handlers script.

**Comment by BratwurstMitSenf** [comment]
I just downloaded the latest 8.0.0 Pre Release from the Releases-Page. But once I get home, I can give it a quick try with the sources from the master-branch.

**Comment by andrewmcwatters** [comment]
Cool, should be roughly the same. I'll work on this tonight after work. Super appreciative about the report, thanks!

**Comment by BratwurstMitSenf** [comment]
No problem :smile:

**Comment by andrewmcwatters** [comment]
This issue has been obsoleted. Please see https://gitter.im/Planimeter/grid-sdk
