### ISSUE TITLE
Error on player move when r_draw_path is set to 1

### ISSUE THREAD

**Issue by BratwurstMitSenf** [Planimeter/grid-sdk#81]
Hey, it's me again. I found another booboo. :wink: 
The following error is thrown when i set r_draw_path to 1 in the console and then move the player (either wasd or a mouseclick will do the trick).
![err](https://cloud.githubusercontent.com/assets/3192999/18561433/23e8105a-7b80-11e6-9519-8505cb6b7bad.png)

I didn't look into what the cause might be yet. I'll add a comment when i have the time.

Gotta stop playing aroung now. I'm the only one left at the office.
Too lazy to drive home... :laughing:

**Comment by andrewmcwatters** [comment]
This issue has been obsoleted. Please see https://gitter.im/Planimeter/grid-sdk
