### ISSUE TITLE
Player states are currently desynced

### ISSUE THREAD

**Issue by ryan-kingstone** [Planimeter/grid-sdk#9]
![screenshot 2015-05-04 22 02 19](https://cloud.githubusercontent.com/assets/4886476/7461286/5c53ac12-f2a9-11e4-92ba-c86cbaaa7de8.png)

The middle one is the last client that connected.

**Comment by andrewmcwatters** [comment]
Thank you for formally reporting this issue, I've neglected to do it. This is a part of a major update to sync entities on player connect. I'm promoting this to high priority; it's sort of embarrassing to even have this issue at the moment. I apologize.

**Comment by andrewmcwatters** [comment]
Going to try my best to have this resolved tonight for quick turnaround time.

**Comment by andrewmcwatters** [comment]
I tried to get this taken care of on the day it was reported but had very little time to do so, scheduling this for Friday/Saturday at the latest.

**Comment by andrewmcwatters** [comment]
Fixed in `19b68ed`
